### ISSUE TITLE
Set the GitHub repo description and website

### ISSUE THREAD

**Issue by dandv** [maximilianschmitt/cssman#2]
The website could be https://www.npmjs.com/package/cssman

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by maximilianschmitt** [comment]
Done, thanks!
